name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  release:
    name: Create release
    permissions:
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: gh release create --draft v0.01 --title v0.01
        
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build
        run: gcc 1.c

      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.SUPERSECRET }}
        run: gh release upload v0.01 ./a.out
