name: Build
run-name: Build And Release a.out

on:
  workflow_dispatch:
    inputs:
      launchpad:
        description: use launchpad
        required: true
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - mixtile-core3588e

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install -y build-essential gcc-aarch64-linux-gnu bison \
          qemu-user-static qemu-system-arm qemu-efi u-boot-tools binfmt-support \
          debootstrap flex libssl-dev bc rsync kmod cpio xz-utils fakeroot parted \
          udev dosfstools uuid-runtime git-lfs device-tree-compiler python2 python3 \
          python-is-python3 fdisk bc debhelper python3-pyelftools python3-setuptools \
          python3-distutils python3-pkg-resources swig libfdt-dev libpython3-dev

      - name: Build a.out
        shell: bash
        run: gcc 1.c


      - name: Build Release
	id: create_release
        uses: actions/create-release@v1
	env:
	  GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
  
      - name: Upload Binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./a.out
          asset_name: a.out
          if-no-files-found: error

     
        
      - name: Clean cache
        shell: bash
        run: sync && rm -rf ./a.out && sync
