name: Build and Upload Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up GCC
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Compile Binary
        run: gcc 1.c -o binary

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Binary
        id: upload_binary
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./binary
          asset_name: binary

      - name: Get Binary URL
        run: echo "Binary URL: ${{ steps.upload_binary.outputs.asset_url }}"
